# Generated by Django 2.2.5 on 2019-09-18 10:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('price_per_day', models.FloatField()),
                ('weekly_discount', models.FloatField(null=True)),
            ],
        ),
    ]
